spring:
  datasource:
    url: jdbc:h2:./db_prod;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level:
    com.back: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO